---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS: # -Xms256m -Xmx512m
  MAVEN_CONFIG: # "-s source-code/ci/local/settings.xml"
  MAVEN_BASEDIR: source-code

inputs:
  - name: source-code

outputs:
  - name: output-dir

run:
  path: source-code/ci/tasks/build.sh
